---
- name: App Install 
  hosts: all
  
  vars_files: app-install-vars.yml

  roles:
    - jacek.custom_app.mariadb
    - jacek.custom_app.nginx
    - jacek.custom_app.phpfpm
    - jacek.custom_app.wordpress